### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by michelvosje** [michelvosje/Hacktoberfest-2016-Game#1]
Be the first to come up with an idea for a game. It doesn't matter what it is. Keep in mind that the game should stay simple so it can be completed before the end of the month. 

Submit your changes with your ideas to the Readme.md. After that I will create issues with the Hacktoberfest label so others can start developing.

**Comment by SilentFlame** [comment]
Can we build a simple Donkey-Kong game for terminal environment, developed in python.

Where can I submit that Idea?
as a PR ?

**Comment by michelvosje** [comment]
Hey HackerSpirit  else already did a PR. I didn't have time yet to create the following tickets. If he adds the #2

**Comment by HackersSpirit** [comment]
@michelvosje : Hi new to github. Can you please tell me about how to add reference to the ticket.

**Comment by HackersSpirit** [comment]
#4 Update README.md
#2 Update game idea
